set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED TRUE)

set(CMAKE_C_STANDARD 23)
set(CMAKE_C_STANDARD_REQUIRED TRUE)

message(STATUS "Cxx Standard: ${CMAKE_CXX_STANDARD} Required: ${CMAKE_CXX_STANDARD_REQUIRED}")
message(STATUS "C Standard: ${CMAKE_C_STANDARD} Required: ${CMAKE_C_STANDARD_REQUIRED}")

message(STATUS "Compiler C: ${CMAKE_C_COMPILER}")
message(STATUS "Compiler CXX: ${CMAKE_CXX_COMPILER}")
